const cards=document.querySelector('#cards');const featured=document.querySelector('#featuredCards');const search=document.querySelector('#search');const typeSelect=document.querySelector('#typeSelect');const brandSelect=document.querySelector('#brandSelect');const strengthSelect=document.querySelector('#strengthSelect');const aromaSelect=document.querySelector('#aromaSelect');const resultCount=document.querySelector('#resultCount');let products=[];
const fallback=[{id:'demo-virginia',marca:'Pipateka',nombre:'Virginia Dorado',tipo:'Virginia',imagen_local:'assets/images/virginia.svg',resumen_editorial:'Ficha de demostración.',valoracion_comunidad:8.5},{id:'demo-english',marca:'Pipateka',nombre:'English No. 7',tipo:'English',imagen_local:'assets/images/english.svg',resumen_editorial:'Ficha de demostración.',valoracion_comunidad:8.0}];
const slug=p=>p.id||`${p.marca||''}-${p.nombre||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function unique(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function optionList(select,items,label){if(!select)return;select.innerHTML=`<option value="${label==='Marca'?'Todas':'Todos'}">${label}</option>`+items.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function setupFilters(){optionList(typeSelect,unique(products.map(p=>p.tipo)),'Tipos');optionList(brandSelect,unique(products.map(p=>p.marca)),'Marca');optionList(strengthSelect,unique(products.map(p=>p.fuerza)),'Fuerza');optionList(aromaSelect,unique(products.map(p=>p.aromatizacion)),'Aromatización')}
function filtered(){const q=(search?.value||'').toLowerCase().trim();return products.filter(p=>{const haystack=`${p.marca||''} ${p.nombre||''} ${p.tipo||''} ${(p.composicion||[]).join(' ')} ${p.resumen_editorial||''}`.toLowerCase();return(!q||haystack.includes(q))&&(!typeSelect.value||typeSelect.value==='Todos'||p.tipo===typeSelect.value)&&(!brandSelect.value||brandSelect.value==='Todas'||p.marca===brandSelect.value)&&(!strengthSelect.value||strengthSelect.value==='Todas'||p.fuerza===strengthSelect.value)&&(!aromaSelect.value||aromaSelect.value==='Todas'||p.aromatizacion===aromaSelect.value)})}
function productCard(p,compact=false){const rating=p.valoracion_comunidad?`★ ${esc(p.valoracion_comunidad)}`:'Ficha';const count=p.numero_resenas?` (${esc(p.numero_resenas)})`:'';if(compact)return `<article class="featured-card"><img src="${esc(p.imagen_local||'assets/images/hero.svg')}" alt="Representación local de ${esc(p.nombre)}"><div class="featured-body"><div class="brand-name">${esc(p.marca)}</div><h3>${esc(p.nombre)}</h3><div class="meta">${esc(p.tipo||'Sin clasificar')} · ${esc((p.composicion||[]).slice(0,2).join('/'))}</div><div class="rating"><b>★</b> ${esc(p.valoracion_comunidad||'—')}${count}</div><div class="strength">●●○ ${esc(p.fuerza||'Media')}</div></div></article>`;const composition=(p.composicion||[]).length?`<p><strong>Composición:</strong> ${esc(p.composicion.join(', '))}</p>`:'';return `<article class="card"><img src="${esc(p.imagen_local||'assets/images/hero.svg')}" alt="Representación local de ${esc(p.nombre)}"><div class="card-body"><span class="tag">${esc(p.tipo||'Sin clasificar')}</span><h3>${esc(p.nombre)}</h3><p><strong>${esc(p.marca)}</strong></p>${composition}<p>${esc(p.resumen_editorial||'Ficha en investigación.')}</p><div class="scores"><span class="score">Comunidad <b>${rating}${count}</b></span>${p.fuerza?`<span class="score">Fuerza <b>${esc(p.fuerza)}</b></span>`:''}${p.corte?`<span class="score">Corte <b>${esc(p.corte)}</b></span>`:''}</div><a class="card-link" href="producto.html?id=${encodeURIComponent(slug(p))}">Ver ficha completa →</a></div></article>`}
function render(){const list=filtered();if(resultCount)resultCount.textContent=`${list.length} resultados`;if(featured)featured.innerHTML=products.slice(0,6).map(p=>productCard(p,true)).join('');if(!cards)return;if(!list.length){cards.innerHTML='<div class="empty">No hay resultados con esos criterios.</div>';return}cards.innerHTML=list.map(p=>productCard(p)).join('')}
async function load(){try{const r=await fetch('data/catalogo.json');if(!r.ok)throw Error('catalogo');const data=await r.json();products=data.products||[]}catch(e){products=fallback}setupFilters();render()}
[search,typeSelect,brandSelect,strengthSelect,aromaSelect].filter(Boolean).forEach(el=>el.addEventListener(el===search?'input':'change',render));document.querySelector('#searchButton')?.addEventListener('click',render);load();