const $=s=>document.querySelector(s);const cards=$('#cards'),search=$('#search'),typeSelect=$('#typeSelect'),brandSelect=$('#brandSelect'),strengthSelect=$('#strengthSelect'),aromaSelect=$('#aromaSelect'),cutSelect=$('#cutSelect'),sortSelect=$('#sortSelect'),typeTiles=$('#typeTiles'),brandTiles=$('#brandTiles');let products=[],brandIndex=[];const state={q:'',type:'Todos',brand:'Todas',strength:'Todas',aroma:'Todas',cut:'Todos',sort:'featured'};
const fallback=[{id:'demo-virginia',marca:'Virginia Dorado',nombre:'Virginia Dorado',tipo:'Virginia',composicion:['Virginia'],fuerza:'Media',aromatizacion:'Ninguna',corte:'Flake',valoracion_comunidad:8.5,numero_resenas:245,resumen_editorial:'Ficha de demostración.'},{id:'demo-english',marca:'English No. 7',nombre:'English No. 7',tipo:'English',composicion:['Latakia','Oriental/Turkish','Virginia'],fuerza:'Media-Fuerte',aromatizacion:'Ninguna',corte:'Ribbon',valoracion_comunidad:8.0,numero_resenas:190,resumen_editorial:'Ficha de demostración.'}];
const slug=p=>p.id||`${p.marca||''}-${p.nombre||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const uniq=a=>[...new Set(a.filter(Boolean))];const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function locale(){return localStorage.getItem('pipateka-lang')||'es'}function T(k){return window.pipaT?window.pipaT(k):k}function V(v){return window.pipaValue?window.pipaValue(v):v}
const EXTRA={es:{trust1a:'8.500+ tabacos de referencia',trust1b:'de 667 marcas indexadas',trust2a:'Valoraciones reales',trust2b:'de la comunidad',trust3a:'Información verificada',trust3b:'y actualizada',trust4a:'Disponibilidad en Europa',trust4b:'por país y mercado',trust5a:'Guía y recursos',trust5b:'para conocer el tabaco de pipa',legal:'Aviso legal',privacy:'Privacidad',contact:'Contacto',about:'Sobre Pipateka'},en:{trust1a:'8,500+ reference tobaccos',trust1b:'from 667 indexed brands',trust2a:'Real ratings',trust2b:'from the community',trust3a:'Verified information',trust3b:'kept up to date',trust4a:'European availability',trust4b:'by country and market',trust5a:'Guides & resources',trust5b:'to learn about pipe tobacco',legal:'Legal notice',privacy:'Privacy',contact:'Contact',about:'About Pipateka'},pt:{trust1a:'8.500+ tabacos de referência',trust1b:'de 667 marcas indexadas',trust2a:'Avaliações reais',trust2b:'da comunidade',trust3a:'Informação verificada',trust3b:'e atualizada',trust4a:'Disponibilidade na Europa',trust4b:'por país e mercado',trust5a:'Guias e recursos',trust5b:'para conhecer o tabaco de cachimbo',legal:'Aviso legal',privacy:'Privacidade',contact:'Contacto',about:'Sobre a Pipateka'},de:{trust1a:'8.500+ Referenztabake',trust1b:'von 667 erfassten Marken',trust2a:'Echte Bewertungen',trust2b:'aus der Community',trust3a:'Geprüfte Informationen',trust3b:'und aktuell',trust4a:'Verfügbarkeit in Europa',trust4b:'nach Land und Markt',trust5a:'Ratgeber & Ressourcen',trust5b:'über Pfeifentabak',legal:'Impressum',privacy:'Datenschutz',contact:'Kontakt',about:'Über Pipateka'},zh:{trust1a:'8,500+ 种参考斗烟',trust1b:'来自 667 个品牌',trust2a:'真实评分',trust2b:'来自社区',trust3a:'已验证信息',trust3b:'持续更新',trust4a:'欧洲市场信息',trust4b:'按国家和市场',trust5a:'指南与资源',trust5b:'了解斗烟',legal:'法律声明',privacy:'隐私',contact:'联系',about:'关于 Pipateka'}};
function applyExtras(){const d=EXTRA[locale()]||EXTRA.es;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(d[k]!=null)el.textContent=d[k]});}
function collator(){const map={es:'es-ES',en:'en-US',pt:'pt-PT',de:'de-DE',zh:'zh-CN'};return new Intl.Collator(map[locale()]||'es-ES',{usage:'sort',sensitivity:'base',numeric:true,ignorePunctuation:true})}
function values(key){return uniq(products.flatMap(p=>Array.isArray(p[key])?p[key]:[p[key]]))}
function fill(select,items,allValue,allLabel){select.innerHTML=`<option value="${esc(allValue)}">${esc(allLabel)}</option>`+items.sort(collator().compare).map(x=>`<option value="${esc(x)}">${esc(V(x))}</option>`).join('')}
function buildFilters(){fill(typeSelect,values('tipo'),'Todos',T('all'));const indexed=brandIndex.map(x=>x.marca);fill(brandSelect,uniq([...indexed,...products.map(p=>p.marca)]),'Todas',T('allFem'));fill(strengthSelect,values('fuerza'),'Todas',T('allFem'));fill(aromaSelect,values('aromatizacion'),'Todas',T('allFem'));fill(cutSelect,values('corte'),'Todos',T('all'));renderTiles();updateSortOptions()}
function updateSortOptions(){if(!sortSelect)return;const d=window.PIPA_I18N?.[locale()]||{};sortSelect.innerHTML=`<option value="featured">${d.featuredSort||'Featured'}</option><option value="rating">${d.ratingSort||'Top rated'}</option><option value="reviews">${d.reviewsSort||'Most reviewed'}</option><option value="name-asc">${d.nameAsc||'Name A–Z'}</option><option value="name-desc">${d.nameDesc||'Name Z–A'}</option>`;sortSelect.value=state.sort}
function categoryMatch(p,type){if(type==='Todos')return true;const hay=[p.tipo,...(p.composicion||[])].join(' ').toLowerCase();return hay.includes(type.toLowerCase())}
function filtered(){let list=products.filter(p=>categoryMatch(p,state.type)&&(state.brand==='Todas'||p.marca===state.brand)&&(state.strength==='Todas'||p.fuerza===state.strength)&&(state.aroma==='Todas'||p.aromatizacion===state.aroma)&&(state.cut==='Todos'||p.corte===state.cut));if(state.q)list=list.filter(p=>[p.marca,p.nombre,p.tipo,p.resumen_editorial,...(p.composicion||[])].join(' ').toLowerCase().includes(state.q));if(state.sort==='rating')list.sort((a,b)=>(b.valoracion_comunidad||0)-(a.valoracion_comunidad||0));if(state.sort==='reviews')list.sort((a,b)=>(b.numero_resenas||0)-(a.numero_resenas||0));if(state.sort==='name-asc')list.sort((a,b)=>collator().compare(String(a.nombre||''),String(b.nombre||'')));if(state.sort==='name-desc')list.sort((a,b)=>collator().compare(String(b.nombre||''),String(a.nombre||'')));return list}
function tinClass(p){const t=(p.tipo||'').toLowerCase();return t.includes('virginia')?'virginia':t.includes('english')||t.includes('balkan')?'english':''}
function card(p){const q=window.pipaProduct?window.pipaProduct(p):p;const rating=Number(p.valoracion_comunidad||0).toFixed(1);const reviews=p.numero_resenas?`(${p.numero_resenas.toLocaleString(locale()==='zh'?'zh-CN':locale())})`:'';const strength=q.fuerza||T('pending');const composition=(q.composicion||[]).slice(0,2).join('/');const square=(p.nombre||'').toLowerCase().includes('flake');return `<article class="product-card"><a href="producto.html?id=${encodeURIComponent(slug(p))}" class="product-link"><div class="product-visual"><div class="tin ${tinClass(p)} ${square?'square':''}"><span>${esc(p.marca||'Pipateka')}<br><small>${esc(p.nombre||T('product'))}</small></span></div></div><div class="product-info"><span class="brand">${esc(p.marca||'Marca')}</span><h3>${esc(p.nombre||T('product'))}</h3><div class="meta">${esc(q.tipo||'')} &nbsp;·&nbsp; ${esc(composition||T('compositionPending'))}</div><div class="rating"><span class="star">★</span><b>${rating}</b> <span>${reviews}</span></div><div class="strength"><span class="dots"><i class="on"></i><i class="on"></i><i></i></span>${esc(strength)} <span class="arrow">${T('arrow')}</span></div></div></a></article>`}
function render(){const list=filtered();cards.innerHTML=list.length?list.slice(0,6).map(card).join(''):`<div class="empty">${T('noResults')}</div>`}
function renderTiles(){const preferred=['Virginia','Virginia/Perique','Virginia/Burley','English','Balkan','Aromatic'];typeTiles.innerHTML=preferred.map(t=>`<a class="type-tile" href="#catalogo" data-type-tile="${esc(t)}"><span>${esc(V(t))}</span><em>→</em></a>`).join('');const brands=(brandIndex.length?brandIndex.map(x=>x.marca):uniq(products.map(p=>p.marca))).sort(collator().compare).slice(0,6);brandTiles.innerHTML=brands.map(b=>`<a class="brand-tile" href="#catalogo" data-brand-tile="${esc(b)}">${esc(b)}</a>`).join('')}
function sync(){typeSelect.value=state.type;brandSelect.value=state.brand;strengthSelect.value=state.strength;aromaSelect.value=state.aroma;cutSelect.value=state.cut;sortSelect.value=state.sort;render()}
search?.addEventListener('input',e=>{state.q=e.target.value.toLowerCase().trim();render()});$('#searchBtn')?.addEventListener('click',()=>{state.q=(search.value||'').toLowerCase().trim();render()});[typeSelect,brandSelect,strengthSelect,aromaSelect,cutSelect,sortSelect].forEach(el=>el?.addEventListener('change',()=>{state.type=typeSelect.value;state.brand=brandSelect.value;state.strength=strengthSelect.value;state.aroma=aromaSelect.value;state.cut=cutSelect.value;state.sort=sortSelect.value;render()}));
$('#moreFilters')?.addEventListener('click',()=>{const box=$('#extraFilters');box.hidden=!box.hidden});$('#resetFilters')?.addEventListener('click',()=>{Object.assign(state,{q:'',type:'Todos',brand:'Todas',strength:'Todas',aroma:'Todas',cut:'Todos',sort:'featured'});search.value='';buildFilters();sync()});document.addEventListener('click',e=>{const t=e.target.closest('[data-type-tile]');const b=e.target.closest('[data-brand-tile]');if(t){state.type=t.dataset.typeTile;sync();document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth'})}if(b){state.brand=b.dataset.brandTile;sync();document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth'})}if(e.target.closest('[data-focus-search]')){search.focus();document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth'})}if(e.target.closest('[data-clear]')){Object.assign(state,{q:'',type:'Todos',brand:'Todas',strength:'Todas',aroma:'Todas',cut:'Todos',sort:'featured'});search.value='';buildFilters();sync()}});
document.addEventListener('pipateka-language',()=>{applyExtras();buildFilters();sync()});
async function load(){try{const [r,b]=await Promise.all([fetch('data/catalogo.json'),fetch('data/marcas.json')]);if(!r.ok)throw Error();const data=await r.json();products=data.products||[];if(b.ok){const bd=await b.json();brandIndex=bd.marcas||[]}}catch(e){try{const r=await fetch('data/catalogo.json');const data=await r.json();products=data.products||[]}catch(_){products=fallback}}applyExtras();buildFilters();render()}load();
