(() => {
  'use strict';
  // La portada trabaja solo con la BBDD editorial. El catálogo completo vive en catalogo.html.
  const EDITORIAL_ITEMS = [['Peterson','Nightcap'],['Peterson','Early Morning Pipe'],['Samuel Gawith','1792 Flake'],['Ashton','Winding Road'],["Rattray's",'Black Mallory'],['Mac Baren','Navy Flake'],['Mac Baren','Plumcake'],['Mac Baren','Dark Twist'],['Mac Baren','Club Blend'],['Peterson','University Flake'],['Samuel Gawith','Full Virginia Flake'],['Samuel Gawith','HH Latakia Flake']];
  const isEditorialItem = item => EDITORIAL_ITEMS.some(([brand,name]) => normalize(item.marca)===normalize(brand) && normalize(item.nombre)===normalize(name));
  const isFullCatalog = document.body.classList.contains('catalog-page');
  const state = { all:[...BBDD_TABACOS].filter(item=>isFullCatalog || isEditorialItem(item)), query:'', type:'', sort:'popularidad' };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stars=v=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)return '☆☆☆☆☆';const c=Math.max(0,Math.min(5,n));return '★'.repeat(Math.round(c))+'☆'.repeat(5-Math.round(c))};
  const displayRating=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?`${n.toFixed(2)}/4`:'Sin datos'};
  const displayStrength=(v,label)=>label&&String(label).trim()?String(label):(()=>{const n=Number(v);return Number.isFinite(n)&&n>0?`${n}/5`:'Sin datos'})();
  const strength=v=>Array.from({length:5},(_,i)=>`<i class="${i<Number(v)?'on':''}"></i>`).join('');
  const card=item=>`<article class="tobacco-card" data-card-id="${esc(item.id)}" tabindex="0" role="button" aria-label="Abrir ficha de ${esc(item.nombre)}"><div class="card-image"><span class="type-badge">${esc(item.tipo)}</span><img src="${esc(item.imagen_marca||item.imagen)}" alt="Imagen de marca de ${esc(item.marca)} para ${esc(item.nombre)}"></div><div class="card-body"><div class="card-brand">${esc(item.marca)}</div><h3>${esc(item.nombre)}</h3><div class="card-meta">${esc(item.corte)} · ${esc(item.aroma)}</div><div class="rating-line"><span class="stars">${stars(Number(item.valoracion)*1.25)}</span><span>${displayRating(item.valoracion)}</span></div><div class="rating-line"><span>Fuerza</span><span class="strength-dots">${strength(item.fuerza)}</span></div></div></article>`;
  function filtered(){const q=normalize(state.query);let rows=state.all.filter(x=>(!q||normalize([x.nombre,x.marca,x.tipo,x.corte,x.composicion].join(' ')).includes(q))&&(!state.type||normalize(x.tipo).includes(normalize(state.type))));if(state.sort==='valoracion')rows.sort((a,b)=>Number(b.valoracion)-Number(a.valoracion));else if(state.sort==='nombre')rows.sort((a,b)=>normalize(a.nombre).localeCompare(normalize(b.nombre),'es'));else rows.sort((a,b)=>Number(b.popularidad)-Number(a.popularidad));return rows}
  function bindCards(root){$$('.tobacco-card',root).forEach(el=>{el.addEventListener('click',()=>openDetail(el.dataset.cardId));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(el.dataset.cardId)}})})}
  function bindImageFallbacks(root){$$('img[data-fallback]',root).forEach(img=>img.addEventListener('error',()=>{if(img.dataset.fallbackApplied)return;img.dataset.fallbackApplied='1';img.src=img.dataset.fallback}, {once:true}))}
  function renderCatalog(){const grid=$('#catalogGrid');if(!grid)return;const rows=filtered();$('#resultCount').textContent=`${rows.length.toLocaleString('es-ES')} fichas visibles`;grid.innerHTML=rows.length?rows.map(item=>card({...item, imagen:item.imagen||'assets/tins/editorial-tin.svg'}).replace('<img ','<img data-fallback="assets/tins/editorial-tin.svg" ')).join(''):'<div class="empty-state">No hay fichas que coincidan con la búsqueda. Prueba otro término o restablece los filtros.</div>';bindCards(grid);bindImageFallbacks(grid)}
  function renderFeatured(){const grid=$('#featuredGrid');if(!grid)return;grid.innerHTML=state.all.slice().sort((a,b)=>b.popularidad-a.popularidad).slice(0,6).map(item=>card({...item, imagen:item.imagen||'assets/tins/editorial-tin.svg'}).replace('<img ','<img data-fallback="assets/tins/editorial-tin.svg" ')).join('');bindCards(grid);bindImageFallbacks(grid)}
  function openDetail(id){const item=state.all.find(x=>x.id===id);if(!item||!$('#detailModal'))return;$('#detailImage').src=item.imagen_marca||item.imagen||'assets/tins/editorial-tin.svg';$('#detailImage').alt=`Imagen de marca de ${item.marca} · ${item.nombre}`;$('#detailImage').onerror=()=>{if($('#detailImage').dataset.fallbackApplied)return;$('#detailImage').dataset.fallbackApplied='1';$('#detailImage').src='assets/tins/editorial-tin.svg'};$('#detailBrand').textContent=item.marca;$('#detailName').textContent=item.nombre;const specs=[['Tipo de mezcla',item.tipo],['Corte',item.corte],['Fuerza',displayStrength(item.fuerza,item.fuerza_label)],['Aromatización',item.aromatizacion],['Nota de estancia',item.nota_estancia],['Sabor / perfil',item.sabor],['Composición',item.composicion],['País',item.pais],['Producción',item.produccion],['Formato',item.packaging],['Mezclado por',item.mezclado_por],['Fabricado por',item.fabricante],['Disponibilidad',item.disponibilidad],['Valoración comunitaria',displayRating(item.valoracion)],['Reseñas registradas',Number(item._resenas_fuente||0).toLocaleString('es-ES')],['Popularidad',`${item.popularidad}/100`]];$('#detailSpecs').innerHTML=specs.map(([a,b])=>`<div class="spec"><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('');const reviews=item.reseñas||[];$('#reviewsList').innerHTML=reviews.length?reviews.map(r=>`<div class="review"><div class="review-head"><strong>${esc(r.usuario)}</strong><span>${esc(r.fecha)} · <span class="stars">${stars(r.puntuacion)}</span></span></div><p>${esc(r.texto)}</p></div>`).join(''):'<div class="review"><p>No hay reseñas textuales asociadas a esta ficha en el índice local.</p></div>';$('#communityNote').textContent='Las entradas de esta demo son síntesis editoriales de opiniones publicadas por la comunidad; no se presentan como testimonios literales ni como usuarios identificables.';$('#detailModal').classList.add('is-open');document.body.classList.add('modal-lock');$('#modalClose')?.focus()}
  function closeDetail(){$('#detailModal')?.classList.remove('is-open');document.body.classList.remove('modal-lock')}
  function updateMetrics(){
    const blendCount=$('#localBlendCount');
    if(blendCount) blendCount.textContent=state.all.length.toLocaleString('es-ES');
  }
  function updateSearchSuggestions(){const list=$('#catalogSearchSuggestions');if(!list)return;const values=[...new Set(BBDD_TABACOS.flatMap(x=>[x.marca,x.nombre,x.tipo,x.corte,x.aroma,x.composicion].filter(Boolean).map(String)))].sort((a,b)=>a.localeCompare(b,'es'));list.innerHTML=values.map(v=>'<option value="'+esc(v)+'"></option>').join('')}
  function editDistance(a,b){const aa=normalize(a),bb=normalize(b);if(!aa)return bb.length;const row=Array.from({length:bb.length+1},(_,i)=>i);for(let i=1;i<=aa.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=bb.length;j++){const cur=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(aa[i-1]===bb[j-1]?0:1));prev=cur}}return row[bb.length]}
  function searchHint(){const q=normalize(state.query);const hint=$('#searchHint');if(!hint)return;if(!q||filtered().length)return hint.textContent='';const candidates=[...new Set(BBDD_TABACOS.flatMap(x=>[x.marca,x.nombre].filter(Boolean).map(String)))];const best=candidates.map(v=>({v,d:editDistance(q,v)})).sort((a,b)=>a.d-b.d)[0];hint.textContent=best&&best.d<=Math.max(2,Math.floor(q.length/3))?'¿Quizá quisiste decir «'+best.v+'»?':''}
  function setupControls(){const search=$('#mainSearch'),type=$('#typeFilter'),sort=$('#sortSelect');if(search){updateSearchSuggestions();search.addEventListener('input',e=>{state.query=e.target.value;renderCatalog();renderFeatured();updateMetrics();searchHint()});$('#searchButton')?.addEventListener('click',()=>{state.query=search.value;renderCatalog();document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth'});search.focus()})}if(type){const types=[...new Set(BBDD_TABACOS.map(x=>x.tipo))].sort((a,b)=>a.localeCompare(b,'es'));type.innerHTML='<option value="">Todos los tipos</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');type.addEventListener('change',e=>{state.type=e.target.value;renderCatalog()})}if(sort){sort.innerHTML='<option value="popularidad">🔥 Más Populares</option><option value="valoracion">★ Mejor valorados</option><option value="nombre">Nombre (A-Z)</option>';sort.value='popularidad';sort.addEventListener('change',e=>{state.sort=e.target.value;renderCatalog()})}$('#clearFilters')?.addEventListener('click',()=>{state.query='';state.type='';state.sort='popularidad';if(search)search.value='';if(type)type.value='';if(sort)sort.value='popularidad';renderCatalog();renderFeatured()});$('#modalClose')?.addEventListener('click',closeDetail);$('#detailModal')?.addEventListener('click',e=>{if(e.target.id==='detailModal')closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});renderCatalog();renderFeatured()}
  document.addEventListener('DOMContentLoaded',setupControls);
})();
