(() => {
  'use strict';
  // La portada trabaja solo con la BBDD editorial. El catálogo completo vive en catalogo.html.
  const state = { all:[...BBDD_TABACOS], query:'', type:'', sort:'popularidad' };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stars=v=>{const n=Math.max(0,Math.min(5,Number(v)||0));return '★'.repeat(Math.round(n))+'☆'.repeat(5-Math.round(n))};
  const strength=v=>Array.from({length:5},(_,i)=>`<i class="${i<Number(v)?'on':''}"></i>`).join('');
  const card=item=>`<article class="tobacco-card" data-card-id="${esc(item.id)}" tabindex="0" role="button" aria-label="Abrir ficha de ${esc(item.nombre)}"><div class="card-image"><span class="type-badge">${esc(item.tipo)}</span><img src="${esc(item.imagen)}" alt="Ilustración editorial de ${esc(item.marca)} ${esc(item.nombre)}"></div><div class="card-body"><div class="card-brand">${esc(item.marca)}</div><h3>${esc(item.nombre)}</h3><div class="card-meta">${esc(item.corte)} · ${esc(item.aroma)}</div><div class="rating-line"><span class="stars">${stars(Number(item.valoracion)*1.25)}</span><span>${Number(item.valoracion).toFixed(2)}/4</span></div><div class="rating-line"><span>Fuerza</span><span class="strength-dots">${strength(item.fuerza)}</span></div></div></article>`;
  function filtered(){const q=normalize(state.query);let rows=state.all.filter(x=>(!q||normalize([x.nombre,x.marca,x.tipo,x.corte,x.composicion].join(' ')).includes(q))&&(!state.type||normalize(x.tipo).includes(normalize(state.type))));if(state.sort==='valoracion')rows.sort((a,b)=>Number(b.valoracion)-Number(a.valoracion));else if(state.sort==='nombre')rows.sort((a,b)=>normalize(a.nombre).localeCompare(normalize(b.nombre),'es'));else rows.sort((a,b)=>Number(b.popularidad)-Number(a.popularidad));return rows}
  function bindCards(root){$$('.tobacco-card',root).forEach(el=>{el.addEventListener('click',()=>openDetail(el.dataset.cardId));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(el.dataset.cardId)}})})}
  function renderCatalog(){const grid=$('#catalogGrid');if(!grid)return;const rows=filtered();$('#resultCount').textContent=`${rows.length} fichas editoriales visibles`;grid.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty-state">No hay fichas que coincidan con la búsqueda. Prueba otro término o restablece los filtros.</div>';bindCards(grid)}
  function renderFeatured(){const grid=$('#featuredGrid');if(!grid)return;grid.innerHTML=state.all.slice().sort((a,b)=>b.popularidad-a.popularidad).slice(0,6).map(card).join('');bindCards(grid)}
  function openDetail(id){const item=state.all.find(x=>x.id===id);if(!item||!$('#detailModal'))return;$('#detailImage').src=item.imagen;$('#detailImage').alt=`${item.marca} ${item.nombre}`;$('#detailBrand').textContent=item.marca;$('#detailName').textContent=item.nombre;const specs=[['Tipo de mezcla',item.tipo],['Corte',item.corte],['Fuerza',`${item.fuerza}/5`],['Aroma / nota de estancia',item.aroma],['Composición',item.composicion],['Disponibilidad en Europa',item.disponibilidad],['Valoración',`${Number(item.valoracion).toFixed(2)}/4`],['Popularidad',`${item.popularidad}/100`]];$('#detailSpecs').innerHTML=specs.map(([a,b])=>`<div class="spec"><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('');const reviews=item.reseñas||[];$('#reviewsList').innerHTML=reviews.length?reviews.map(r=>`<div class="review"><div class="review-head"><strong>${esc(r.usuario)}</strong><span>${esc(r.fecha)} · <span class="stars">${stars(r.puntuacion)}</span></span></div><p>${esc(r.texto)}</p></div>`).join(''):'<div class="review"><p>No hay reseñas textuales asociadas a esta ficha en el índice local.</p></div>';$('#communityNote').textContent='Las entradas de esta demo son síntesis editoriales de opiniones publicadas por la comunidad; no se presentan como testimonios literales ni como usuarios identificables.';$('#detailModal').classList.add('is-open');document.body.classList.add('modal-lock');$('#modalClose')?.focus()}
  function closeDetail(){$('#detailModal')?.classList.remove('is-open');document.body.classList.remove('modal-lock')}
  function setupControls(){const search=$('#mainSearch'),type=$('#typeFilter'),sort=$('#sortSelect');if(search){search.addEventListener('input',e=>{state.query=e.target.value;renderCatalog();renderFeatured()});$('#searchButton')?.addEventListener('click',()=>{state.query=search.value;renderCatalog();document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth'});search.focus()})}if(type){const types=[...new Set(BBDD_TABACOS.map(x=>x.tipo))].sort((a,b)=>a.localeCompare(b,'es'));type.innerHTML='<option value="">Todos los tipos</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');type.addEventListener('change',e=>{state.type=e.target.value;renderCatalog()})}if(sort){sort.innerHTML='<option value="popularidad">🔥 Más Populares</option><option value="valoracion">★ Mejor valorados</option><option value="nombre">Nombre (A-Z)</option>';sort.value='popularidad';sort.addEventListener('change',e=>{state.sort=e.target.value;renderCatalog()})}$('#clearFilters')?.addEventListener('click',()=>{state.query='';state.type='';state.sort='popularidad';if(search)search.value='';if(type)type.value='';if(sort)sort.value='popularidad';renderCatalog();renderFeatured()});$('#modalClose')?.addEventListener('click',closeDetail);$('#detailModal')?.addEventListener('click',e=>{if(e.target.id==='detailModal')closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});renderCatalog();renderFeatured()}
  document.addEventListener('DOMContentLoaded',setupControls);
})();
